name: PowerPredict Deploy
on:
  push:
    branches: [ main, api ]
  pull_request:
    branches: [ main, api ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    tests
    - name: Run unit tests (un fichier)
      run: |
        pytest _backend/tests/test_api.py
    # - name: Print Hello
    #   run: |
    #     python _backend/tests/hello.py
